import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>BOOSTAY – Luxury Hotel Social Media PR Platform</title>
        <meta name="description" content="BOOSTAY is the ultra-premium social media PR platform for luxury hotels. Data-driven, viral growth, Fortune 500 quality." />
        <meta property="og:title" content="BOOSTAY – Luxury Hotel Social Media PR Platform" />
        <meta property="og:description" content="BOOSTAY is the ultra-premium social media PR platform for luxury hotels. Data-driven, viral growth, Fortune 500 quality." />
        <meta property="og:image" content="/images/logo1.png" />
        <meta property="og:url" content="https://boostay.com" />
        <meta property="og:type" content="website" />
        <link rel="canonical" href="https://boostay.com" />
        <link rel="robots" href="/robots.txt" />
        <link rel="sitemap" type="application/xml" href="/sitemap.xml" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#578680" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon.png?v=1" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon.png?v=1" />
        <link rel="apple-touch-icon" href="/favicon.png?v=1" />
        <link rel="shortcut icon" href="/favicon.png?v=1" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
